### ISSUE TITLE
AndroidManifest.xml

### ISSUE THREAD

**Issue by andreiciceu** [infobip/push-plugin-unity#1]
After I import the package, I cannot compile the project anymore, due to AndroidManifest.xml being totally overwritten.

**Comment by nmaric** [comment]
Hi @andreiciceu,

You may exclude AndroidManifest.xml when importing package and then unpack it from unitypackage elsewhere and manually merge it, or (perhaps simpler method) temporary move or rename your original AndroidManifest.xml and merge it with our after importing package.

If you have further questions, please contact us on push.support@infobip.com or here.
